# config/routes.yaml

controllers:
    resource: ../src/Controller/
    type: attribute

blog_list:
      path: /blog/{page<\d+>?1} # <\d+> ckecks, if the page element is a decimal; ?1 sets 1 as the default parameter, if there is no parameter
      controller: App\Controller\BlogController::list
      
blog_show:
      path: /blog/{slug}
      controller: App\Controller\BlogController::show
      defaults:
          title: "Hello World"